### ISSUE TITLE
Return `NaN` value if we calculate correlation in same datapoints

### ISSUE THREAD

**Issue by surajrai-dzango** [rubenvar/calculate-correlation#5]
### Reproduction link
https://codesandbox.io/s/happy-knuth-ij1lko?file=/src/index.js

### Steps to reproduce
- Create a same datapoints like [3, 3, 3]
- Calculate the trend/correlation

### What is expected?
- No `NaN` value return while calculating correlation/trend. Value should be `0`

Environment | Info
-- | --
calculate-correlation | v1.2.3
Node | 14.0
System | macOS

**Comment by rubenvar** [comment]
Hello @surajrai-dzango, thanks for taking the time to report this.

After looking into it, I'm not so sure that the returned value in this case should be `0`:

If all points have the same `x` or the same `y` (so the numbers in one of the arrays are all the same, like in your example), when we calculate the correlation there would be a step where we have to divide by 0. Which doesn't result in `0`, but `undefined`. That's why the package is returning `NaN` in this case.

I have checked datasets like this in various calculators online ([this](https://www.socscistatistics.com/tests/pearson/default2.aspx), [this](https://www.statskingdom.com/correlation-calculator.html), [this](http://www.alcula.com/calculators/statistics/correlation-coefficient/), [this](https://mathcracker.com/correlation-coefficient-calculator#results)) and all of them return either `NaN`, `undefined`, or an error in this case, but not `0`, so I think it would not be correct to return that.
